[config]
schemaVersion = "0.0.1"

[package]
namespace = "Gogas1"
name = "NKVDebugMod"
versionNumber = "0.1.0"
description = "Debug tools for NKV"
websiteUrl = "https://github.com/Gogas1/NKVDebugMod"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "0.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
